In [2]:
import tensorflow as tf

In [3]:
print(tf.__version__)

2.15.0


## Create tensors using tf.constant()

### Create Scalar - ndim = 0

In [4]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
scalar.dtype

tf.int32

In [6]:
scalar.shape

TensorShape([])

In [7]:
scalar.ndim

0

### Create Vectors - ndim = 1

In [8]:
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [9]:
vector.shape, vector.ndim

(TensorShape([2]), 1)

### Create Matrix - ndim = 2

In [10]:
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [11]:
matrix.ndim, matrix.shape

(2, TensorShape([2, 2]))

In [12]:
another_matrix = tf.constant([[10., 7.], [3.,2.], [8., 9.]], dtype = tf.float32)

In [13]:
another_matrix.ndim

2

### Create a tensor - ndim >= 0

In [14]:
tensor = tf.constant([[[1,2,3],[4,5,6],[7,8,9]], [[10, 11, 12], [13,14,15], [16,17,1]]])

In [15]:
tensor.ndim

3

## Create tensors using `tf.variable()`

### Creating a vector

In [16]:
changeable_vector = tf.Variable([10, 7])
unchangeable_vector = tf.constant([10, 7])
changeable_vector, unchangeable_vector

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [17]:
changeable_vector[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [18]:
unchangeable_vector[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

## Creating Random Tensors

### Creating a random generator from seed - tf.random.Generator.from_seed(seed_val)

In [19]:
random = tf.random.Generator.from_seed(42)

### Creating a random normal tensor - random.normal(shape = ())

In [20]:
random = random.normal((3, 5))

In [21]:
random

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026, -1.2573844 , -0.23193763],
       [-1.8107855 ,  0.09988727, -0.50998646, -0.7535805 , -0.57166284],
       [ 0.1480774 , -0.23362993, -0.3522796 ,  0.40621263, -1.0523509 ]],
      dtype=float32)>

### Creating a random uniform tensor - random.uniform(shape = ())

In [137]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.uniform((3, 5))
random_1

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0.7493447 , 0.73561966, 0.45230794, 0.49039817, 0.1889317 ],
       [0.52027524, 0.8736881 , 0.46921718, 0.63932586, 0.6467117 ],
       [0.96246755, 0.41009164, 0.86540747, 0.8862978 , 0.27795732]],
      dtype=float32)>

## Shuffle the Order of elements in a tensor

- Sometimes Order of Input might effect the deep learning model learning, that's where shuffling might improve learning.

In [23]:
not_shuffled = tf.constant([[10, 7], [3, 4], [5, 6]])

### Shuffling along the first dimension - tf.random.shuffle()

In [24]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 5,  6]])>

In [25]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 5,  6]])>

### Shuffling along the first dimension using seed - tf.random.set_seed(seed_value), tf.random.shuffle(value, seed = seed_value)

[random_seed](https://www.tensorflow.org/api_docs/python/tf/random/set_seed)

To have reproducible tensors we need to have global seed and operational seed.

In [26]:
tf,random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'set_seed'

In [27]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 5,  6]])>

## Tensors from Numpy Arrays

In [28]:
import numpy as np

### Creating tensors of ones - tf.ones(shape)

In [29]:
tf.ones(shape=(10, 7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

### Creating tensors with zeros - tf.zeros(shape)

In [30]:
tf.zeros((3, 5))

<tf.Tensor: shape=(3, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### Turning numpy arrays into tensors - tf.constant(numpy_array)

The main difference between a numpy arrays and tensorflow tensors is that tensors can be run on a GPU (much faster for numerical computing)

In [31]:
import numpy as np

In [32]:
numpy_A = np.arange(1, 25, dtype=np.int32)

In [33]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [34]:
A = tf.constant(numpy_A, shape = (2, 3, 4))

In [35]:
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

In [36]:
A


<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])>

## Tensor Attributes

### Shape - length of each of the dimensions of a tensor - tensor.shape

In [42]:
rank_4_tensor = tf.zeros((2, 3,4,5))
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

### Rank - 0 for scalar, 1 for vector, 2 for matrix - tensor.ndim

In [43]:
rank_4_tensor = tf.zeros((2, 3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [44]:
rank_4_tensor.ndim

4

### Axis or Dimension - particular dimension of a tensor - tensor[0]

In [45]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

### Size - total number of items in a tensor tf.size(tensor)

In [41]:
tf.size(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=120>

### Datatype of tensor - tensor.dtype

In [46]:
rank_4_tensor.dtype

tf.float32

## Indexing and Expanding Tensor

### Tensors can be indexed as python lists

In [49]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [50]:
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

### Adding a dimension to a tensor - tensor[..., tf.newaxis]

In [51]:
rank_2_tensor = tf.constant([[10, 7], [5, 6]])

In [53]:
rank_2_tensor.ndim

2

In [54]:
rank_2_tensor[: , -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 6])>

In [55]:
rank_3_tensor = rank_2_tensor[..., tf.newaxis]

In [56]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 5],
        [ 6]]])>

### Alternative way to add new axis - tf.expand_dims(tensor, axis = -1) // for adding new dim at the end

In [59]:
tf.expand_dims(rank_2_tensor, axis= -1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 5,  6]]])>

## Manipulating Tensors(tensor Operations)

### Basic Operations(+, -, *, /)

In [63]:
tensor_1 = tf.constant([[10, 7], [5, 6]])

In [64]:
tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  6]])>

In [66]:
tensor_1 + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [15, 16]])>

In [67]:
tensor_1 * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 50,  60]])>

In [68]:
tensor_1 - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-5, -4]])>

### We can use the tensorflow builtin functions as well

In [69]:
tf.add(tensor_1, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [15, 16]])>

In [70]:
tf.multiply(tensor_1, 5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[50, 35],
       [25, 30]])>

In [71]:
tf.reduce_mean(tensor_1)

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [72]:
tf.divide(tensor_1, 10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.5, 0.6]])>

In [75]:
tf.subtract(tensor_1, 11)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-1, -4],
       [-6, -5]])>

## Matrix Multiplication in Tensors

In neural network matrix multiplication is one of the common operations

### Element wise multiplication - tf.multiply() or tensor_1 * tensor_2

In [76]:
tensor_1 * tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [ 25,  36]])>

In [77]:
tf.multiply(tensor_1, tensor_1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [ 25,  36]])>

### Dot Product => tf.matmul(tensor_1 * tensor_2) or tensor_1 @ tensor_2 or tf.tensordot(tensor_1, tensor_2)

In [79]:
tf.matmul(tensor_1, tensor_1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[135, 112],
       [ 80,  71]])>

In [80]:
tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  6]])>

In [81]:
tensor_1 @ tensor_1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[135, 112],
       [ 80,  71]])>

In [82]:
x = tf.constant([[1, 2], [3,4 ], [5, 6]])
y = tf.constant([[7, 8], [9, 10], [11, 12]])
x, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

### Transpose of a tensor => tf.transpose(tensor)

In [85]:
x @ tf.transpose(y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

### Reshaping a tensor => tf.reshape(tensor, shape = ())

In [87]:
x @ tf.reshape(y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [90]:
tf.tensordot(x, tf.transpose(y), axes =  1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

## Changing Type of a tensor => tf.cast(tensor, dtype = tf.)

In [91]:
B = tf.constant([1.7, 7.4])

In [92]:
C = tf.constant([7, 10])

In [94]:
C

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [96]:
D = tf.cast(B, dtype=tf.float16)

In [97]:
D

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

### Change from int32 to float32

In [100]:
E = tf.cast(C, dtype=tf.float32)

In [101]:
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

## Tensor Aggregations
- Aggregating tensors = condensing them from multiple values down to a smaller amount of values

### Get the absolute values => tf.abs(tensor)

In [103]:
D = tf.constant([-7, -10])

In [104]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

### minimum of a tensor => tf.reduce_min(tensor)

In [129]:
np.random.seed(42)
E = tf.constant(np.random.randint(0, 100, size=50))
E, tf.size(E), E.ndim

(<tf.Tensor: shape=(50,), dtype=int32, numpy=
 array([51, 92, 14, 71, 60, 20, 82, 86, 74, 74, 87, 99, 23,  2, 21, 52,  1,
        87, 29, 37,  1, 63, 59, 20, 32, 75, 57, 21, 88, 48, 90, 58, 41, 91,
        59, 79, 14, 61, 61, 46, 61, 50, 54, 63,  2, 50,  6, 20, 72, 38])>,
 <tf.Tensor: shape=(), dtype=int32, numpy=50>,
 1)

In [116]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

### Maximum of a tensor => tf.reduce_max(tensor)

In [118]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=97>

### Mean of a tensor => tf.reduce_mean(tensor)

In [119]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=53>

### Sum of a tensor => tf.reduce_sum(tensor)

In [120]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2676>

### Variance of a tensor => tfp.stats.variance(tensor) => we need tensorflow_probability

In [123]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int32, numpy=813>

### Standard Deviation of a tensor => tf.math.reduce_std(tensor) => tensor should of type float or complex

In [126]:
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=28.519636>

## Find positional maximum and minimum of a tensor

In [140]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])

In [141]:
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

### Find positional maximum => tf.argmax(tensor)

In [142]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [144]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [145]:
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

### Find positional minimum => tf.argmin(tensor)

In [148]:
assert tf.reduce_min(F) == F[tf.argmin(F)]

In [149]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

## Squeezing a tensor(removing all single dimensions) => tf.squeeze(G) => removes all dimensions of 1

In [152]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1, 50))

In [153]:
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [154]:
G_Squeezed = tf.squeeze(G)

In [155]:
G_Squeezed.shape

TensorShape([50])

In [156]:
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

## One hot encoding => tf.one_hot(list, depth)

In [159]:
some_list = [0, 1, 2, 3]
tf.one_hot(some_list, depth= 3)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]], dtype=float32)>

### Specify custom values for one hot encoding - tf.one_hot(indices, depth = int_val, off_value ="", on_value = "")

In [160]:
tf.one_hot(some_list, depth=4, on_value="Yes", off_value="No")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Yes', b'No', b'No', b'No'],
       [b'No', b'Yes', b'No', b'No'],
       [b'No', b'No', b'Yes', b'No'],
       [b'No', b'No', b'No', b'Yes']], dtype=object)>

## More math operations

### Square - tf.square(tensor)

In [161]:
H = tf.range(1, 10)

In [162]:
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [164]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

### Finding Square root => tf.math.sqrt(tensor) => works only with float or complex types

In [166]:
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

### Finding log => tf.math.log(tensor) => works only with float or complex types

In [169]:
tf.math.log(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

## Tensors and Numpy

- One of the main differences between a TensorFlow tensor and a numpy is that a TensorFlow can be run on a TPU or GPU(for faster numerical processing)

### Converting tensor to numpy => tensor.numpy()

In [172]:
tensor_J = tf.constant(np.array([3.,7.,10.]))

In [173]:
tensor_J.numpy()

array([ 3.,  7., 10.])

In [175]:
tf.config.list_physical_devices('GPU')

[]

In [176]:

from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 14035268028164800258
xla_global_id: -1
]


In [177]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]