# Numpy

In [2]:
import numpy as np

## DataTypes & Attributes

### Numpy's main datatype is ndarray

In [3]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)


numpy.ndarray

In [5]:
a2 = np.array([[1, 2.0, 3.3], [4, 5, 6.5]])

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

### finding dimensions of numpy array - ar.shape

In [9]:
a3.shape


(3, 2, 3)

In [10]:
a1.shape


(3,)

In [11]:
a2.shape

(2, 3)

### Finding number of dimensions of numpy array - ar.ndmin

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

### Finding type of values in numpy array - ar.dtype

In [13]:
a2.dtype, a2.dtype, a3.dtype

(dtype('float64'), dtype('float64'), dtype('int32'))

### Finding number of values in numpy array - ar.size

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

### Making pandas series using numpy array - pd.Series(ar)

In [17]:
import pandas as pd
pd.Series(a1)

0    1
1    2
2    3
dtype: int32

## Creating Numpy Arrays

### Creating using list - np.array(list)

In [18]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

### Creating array of Ones - np.ones((5,), dtype=int) or np.ones(shape)

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
ones = np.ones((2, 3))

In [22]:
ones.dtype

dtype('float64')

In [23]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

### Creating numpy array of zeros - np.zeros(shape, dtype)

In [26]:
zeros = np.zeros((2, 3), dtype=float)

In [27]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

### Creating even spaced values numpy array - np.arange(start, stop, step)

In [28]:
range_array = np.arange(0, 10, 2)

In [29]:
range_array

array([0, 2, 4, 6, 8])

### Creating numpy array with random values - np.random.randint(start, stop, size = (3, 5))

In [32]:
random_array = np.random.randint(0, 10, size = (3, 5))

In [33]:
random_array

array([[3, 5, 4, 7, 2],
       [6, 4, 0, 0, 6],
       [9, 4, 3, 8, 4]])

### Creating numpy array with random values ranging from [0.0, 1.0) - np.random.random(size = ()) or np.random.rand(d1, d2, ....)

In [37]:
random_array2 = np.random.random(size = (5, 3))

In [38]:
random_array2

array([[0.40799484, 0.46534829, 0.12977194],
       [0.23410917, 0.37346983, 0.67666114],
       [0.18560398, 0.25809396, 0.46570201],
       [0.02328162, 0.96408593, 0.57705478],
       [0.7232832 , 0.20556649, 0.57676184]])

In [39]:
random_array3 = np.random.rand(5, 3)

In [40]:
random_array3

array([[0.53660668, 0.31283748, 0.83367284],
       [0.42107564, 0.8273376 , 0.68915443],
       [0.2031369 , 0.04569394, 0.78528319],
       [0.22099877, 0.80278951, 0.81406847],
       [0.08950514, 0.16985724, 0.31140641]])

### Getting same numpy random array - np.random.seed(seed_value)

In [47]:
np.random.seed(0)
random_array4 = np.random.randint(10, size = (5, 3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [43]:
random_array4.shape

(5, 3)

In [49]:
np.random.seed(7)
random_array5 = np.random.rand(5, 3)
random_array5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## Viewing Arrays and Matrices

### Finding unique element in the numpy array - np.unique(ar)

In [51]:
np.unique(random_array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Indexing elements of numpy array - ar[:, :] (anything more than 1 dim is called matrix)(any dim is called array)

In [52]:
a1[0], 

1

In [53]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [58]:
a4 = np.random.randint(10, size = (2,3,4,5))
a4

array([[[[0, 5, 3, 0, 5],
         [7, 1, 8, 4, 9],
         [0, 2, 0, 7, 6],
         [2, 9, 9, 5, 1]],

        [[0, 0, 9, 1, 1],
         [5, 3, 2, 0, 4],
         [8, 7, 1, 4, 9],
         [3, 6, 7, 1, 0]],

        [[2, 7, 0, 0, 9],
         [8, 2, 0, 5, 5],
         [0, 9, 0, 8, 4],
         [5, 1, 4, 0, 7]]],


       [[[2, 0, 3, 9, 8],
         [3, 7, 1, 0, 1],
         [4, 6, 1, 0, 1],
         [0, 1, 8, 4, 1]],

        [[6, 8, 5, 2, 4],
         [7, 4, 1, 2, 8],
         [5, 2, 9, 6, 2],
         [5, 7, 7, 5, 5]],

        [[6, 0, 6, 4, 6],
         [2, 6, 8, 7, 0],
         [5, 8, 9, 7, 7],
         [6, 2, 5, 6, 1]]]])

In [59]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [60]:
a4[:, :, :1, :4]

array([[[[0, 5, 3, 0]],

        [[0, 0, 9, 1]],

        [[2, 7, 0, 0]]],


       [[[2, 0, 3, 9]],

        [[6, 8, 5, 2]],

        [[6, 0, 6, 4]]]])

## Manipulating & Comapring Arrays

### Arithmetic Operators - Subject to certain constraints, the smaller array is broadcast across the large array so that they have compatible shapes.

### Arithmetic Operator add - ar1 + ar2 

In [61]:
ones = np.ones(3)

In [62]:
a1 + ones

array([2., 3., 4.])

In [63]:
a1

array([1, 2, 3])

### Arithmetic Operation sub - ar1 - ar2

In [64]:
a1 - ones

array([0., 1., 2.])

### Arithmetic Operator mul - ar1 * ar2

In [65]:
a1 * ones

array([1., 2., 3.])

In [66]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [67]:
a2 * a3

array([[[  1. ,   4. ,   9.9],
        [ 16. ,  25. ,  39. ]],

       [[  7. ,  16. ,  29.7],
        [ 40. ,  55. ,  78. ]],

       [[ 13. ,  28. ,  49.5],
        [ 64. ,  85. , 117. ]]])

In [68]:
a1 / ones

array([1., 2., 3.])

### Arithmetic Operation - floor division ar1 // ar2

In [69]:
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

### Arithmetic Operation square ar1 ** 2 or np.square(ar1)

In [70]:
np.square(a1)

array([1, 4, 9])

### Log operation on numpy array np.log(ar)

In [71]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])